//! The NetworkManager D-Bus calls nmrs does not make: checkpoints,
//! activation, reloading the keyfiles. Only the methods and properties the
//! agent uses, typed as NetworkManager 1.46 documents them
//! (`introspection/org.freedesktop.NetworkManager*.xml`).
//!
//! These are generated by `#[zbus::proxy]`, which is why every call to them
//! is wrapped in `within()` at the call site, in `nm/mod.rs`.

use std::collections::HashMap;

use zbus::zvariant::{ObjectPath, OwnedObjectPath, Value};

use crate::nm::settings::Dict;

/// `NM_CHECKPOINT_CREATE_FLAG_DESTROY_ALL | ..._DELETE_NEW_CONNECTIONS`: a
/// stale checkpoint of ours never blocks a new one, and a profile the
/// change created goes with a rollback. Not `DISCONNECT_NEW_DEVICES`, which
/// would take down a cable plugged in meanwhile.
pub const CHECKPOINT_FLAGS: u32 = 0x1 | 0x2;

/// `NM_ACTIVE_CONNECTION_STATE_ACTIVATED` and `..._DEACTIVATED`.
pub const ACTIVATED: u32 = 2;
pub const DEACTIVATED: u32 = 4;

/// `NM_DEVICE_TYPE_WIFI`.
pub const DEVICE_WIFI: u32 = 2;

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager",
    default_service = "org.freedesktop.NetworkManager",
    default_path = "/org/freedesktop/NetworkManager"
)]
pub trait Manager {
    fn checkpoint_create(
        &self,
        devices: &[ObjectPath<'_>],
        rollback_timeout: u32,
        flags: u32,
    ) -> zbus::Result<OwnedObjectPath>;
    fn checkpoint_rollback(
        &self,
        checkpoint: &ObjectPath<'_>,
    ) -> zbus::Result<HashMap<String, u32>>;
    fn checkpoint_destroy(&self, checkpoint: &ObjectPath<'_>) -> zbus::Result<()>;
    fn get_device_by_ip_iface(&self, iface: &str) -> zbus::Result<OwnedObjectPath>;
    fn activate_connection(
        &self,
        connection: &ObjectPath<'_>,
        device: &ObjectPath<'_>,
        specific_object: &ObjectPath<'_>,
    ) -> zbus::Result<OwnedObjectPath>;
    fn deactivate_connection(&self, active_connection: &ObjectPath<'_>) -> zbus::Result<()>;

    #[zbus(property)]
    fn wireless_enabled(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn wireless_hardware_enabled(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn active_connections(&self) -> zbus::Result<Vec<OwnedObjectPath>>;
    #[zbus(property)]
    fn devices(&self) -> zbus::Result<Vec<OwnedObjectPath>>;
}

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager.Settings",
    default_service = "org.freedesktop.NetworkManager",
    default_path = "/org/freedesktop/NetworkManager/Settings"
)]
pub trait Settings {
    fn get_connection_by_uuid(&self, uuid: &str) -> zbus::Result<OwnedObjectPath>;
    /// Re-read every keyfile directory - `/run` included - and apply what
    /// changed. NetworkManager does not watch them by itself.
    fn reload_connections(&self) -> zbus::Result<bool>;
}

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager.Settings.Connection",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait Profile {
    fn get_settings(&self) -> zbus::Result<Dict>;
}

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager.Device",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait Device {
    #[zbus(property)]
    fn interface(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn device_type(&self) -> zbus::Result<u32>;
    #[zbus(property)]
    fn active_connection(&self) -> zbus::Result<OwnedObjectPath>;
    /// `/` while the device has no DHCPv4 lease.
    #[zbus(property)]
    fn dhcp4_config(&self) -> zbus::Result<OwnedObjectPath>;
}

/// A DHCPv4 lease: every option the server sent, by NetworkManager's name
/// for it (`ntp_servers`, space separated), as strings.
#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager.DHCP4Config",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait Dhcp4Config {
    #[zbus(property)]
    fn options(&self) -> zbus::Result<HashMap<String, zbus::zvariant::OwnedValue>>;
}

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager.Device.Wireless",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait Wireless {
    fn request_scan(&self, options: HashMap<&str, Value<'_>>) -> zbus::Result<()>;

    /// `CLOCK_BOOTTIME` in milliseconds, -1 before the first scan.
    #[zbus(property)]
    fn last_scan(&self) -> zbus::Result<i64>;
}

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager.Connection.Active",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait Active {
    #[zbus(property)]
    fn state(&self) -> zbus::Result<u32>;
    #[zbus(property)]
    fn uuid(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn devices(&self) -> zbus::Result<Vec<OwnedObjectPath>>;

    /// `StateChanged(state, reason)`. Named apart from the `State`
    /// property, whose change stream would otherwise take the same name.
    #[zbus(signal, name = "StateChanged")]
    fn activation(&self, state: u32, reason: u32) -> zbus::Result<()>;
}

/// `NMActiveConnectionStateReason`, in words.
pub fn reason(code: u32) -> String {
    match code {
        2 => "disconnected by request".to_string(),
        3 => "the device disconnected".to_string(),
        5 => "no usable IP configuration (no DHCP answer?)".to_string(),
        6 => "timed out".to_string(),
        9 => "no secrets (wrong password?)".to_string(),
        10 => "login failed (wrong password?)".to_string(),
        11 => "the profile was removed".to_string(),
        12 => "a connection it depends on failed".to_string(),
        14 => "the device went away".to_string(),
        other => format!("NetworkManager reason {other}"),
    }
}
