//! The NetworkManager D-Bus calls nmrs does not make: checkpoints, the
//! in-memory `Update2`, `Save`, `Reapply` and friends. Only the methods and
//! properties the transaction uses, typed as NetworkManager 1.46 documents
//! them (`introspection/org.freedesktop.NetworkManager*.xml`).
//!
//! These are generated by `#[zbus::proxy]`, which is why every call to them
//! is wrapped in `within()` at the call site, in `nm/mod.rs`.

use std::collections::HashMap;

use zbus::zvariant::{ObjectPath, OwnedObjectPath, OwnedValue, Value};

use crate::nm::settings::Dict;

/// `NM_CHECKPOINT_CREATE_FLAG_DESTROY_ALL | ..._DELETE_NEW_CONNECTIONS`: a
/// stale checkpoint of ours never blocks a new one, and a profile the
/// change created goes with a rollback. Not `DISCONNECT_NEW_DEVICES`, which
/// would take down a cable plugged in meanwhile.
pub const CHECKPOINT_FLAGS: u32 = 0x1 | 0x2;

/// `NM_SETTINGS_UPDATE2_FLAG_TO_DISK`.
pub const TO_DISK: u32 = 0x1;
/// `NM_SETTINGS_UPDATE2_FLAG_IN_MEMORY`: a keyfile under `/run`, shadowing
/// the one in `/etc`, which is left untouched until `Save()`.
pub const IN_MEMORY: u32 = 0x2;

/// `NM_ACTIVE_CONNECTION_STATE_ACTIVATED` and `..._DEACTIVATED`.
pub const ACTIVATED: u32 = 2;
pub const DEACTIVATED: u32 = 4;

/// `NM_DEVICE_TYPE_WIFI`.
pub const DEVICE_WIFI: u32 = 2;

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager",
    default_service = "org.freedesktop.NetworkManager",
    default_path = "/org/freedesktop/NetworkManager"
)]
pub trait Manager {
    fn checkpoint_create(
        &self,
        devices: &[ObjectPath<'_>],
        rollback_timeout: u32,
        flags: u32,
    ) -> zbus::Result<OwnedObjectPath>;
    fn checkpoint_rollback(
        &self,
        checkpoint: &ObjectPath<'_>,
    ) -> zbus::Result<HashMap<String, u32>>;
    fn checkpoint_destroy(&self, checkpoint: &ObjectPath<'_>) -> zbus::Result<()>;
    fn get_device_by_ip_iface(&self, iface: &str) -> zbus::Result<OwnedObjectPath>;
    fn activate_connection(
        &self,
        connection: &ObjectPath<'_>,
        device: &ObjectPath<'_>,
        specific_object: &ObjectPath<'_>,
    ) -> zbus::Result<OwnedObjectPath>;
    fn add_and_activate_connection2(
        &self,
        connection: &Dict,
        device: &ObjectPath<'_>,
        specific_object: &ObjectPath<'_>,
        options: HashMap<&str, Value<'_>>,
    ) -> zbus::Result<(
        OwnedObjectPath,
        OwnedObjectPath,
        HashMap<String, OwnedValue>,
    )>;
    fn deactivate_connection(&self, active_connection: &ObjectPath<'_>) -> zbus::Result<()>;

    #[zbus(property)]
    fn wireless_enabled(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_wireless_enabled(&self, enabled: bool) -> zbus::Result<()>;
    #[zbus(property)]
    fn wireless_hardware_enabled(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn active_connections(&self) -> zbus::Result<Vec<OwnedObjectPath>>;
    #[zbus(property)]
    fn devices(&self) -> zbus::Result<Vec<OwnedObjectPath>>;
}

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager.Settings",
    default_service = "org.freedesktop.NetworkManager",
    default_path = "/org/freedesktop/NetworkManager/Settings"
)]
pub trait Settings {
    fn get_connection_by_uuid(&self, uuid: &str) -> zbus::Result<OwnedObjectPath>;
    fn add_connection2(
        &self,
        settings: &Dict,
        flags: u32,
        args: HashMap<&str, Value<'_>>,
    ) -> zbus::Result<(OwnedObjectPath, HashMap<String, OwnedValue>)>;
}

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager.Settings.Connection",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait Profile {
    fn get_settings(&self) -> zbus::Result<Dict>;
    fn get_secrets(&self, setting_name: &str) -> zbus::Result<Dict>;
    fn update2(
        &self,
        settings: &Dict,
        flags: u32,
        args: HashMap<&str, Value<'_>>,
    ) -> zbus::Result<HashMap<String, OwnedValue>>;
    fn save(&self) -> zbus::Result<()>;
    fn delete(&self) -> zbus::Result<()>;

    #[zbus(property)]
    fn unsaved(&self) -> zbus::Result<bool>;
}

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager.Device",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait Device {
    fn reapply(&self, connection: &Dict, version_id: u64, flags: u32) -> zbus::Result<()>;

    #[zbus(property)]
    fn interface(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn device_type(&self) -> zbus::Result<u32>;
    #[zbus(property)]
    fn active_connection(&self) -> zbus::Result<OwnedObjectPath>;
}

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager.Device.Wireless",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait Wireless {
    fn request_scan(&self, options: HashMap<&str, Value<'_>>) -> zbus::Result<()>;

    /// `CLOCK_BOOTTIME` in milliseconds, -1 before the first scan.
    #[zbus(property)]
    fn last_scan(&self) -> zbus::Result<i64>;
}

#[zbus::proxy(
    interface = "org.freedesktop.NetworkManager.Connection.Active",
    default_service = "org.freedesktop.NetworkManager"
)]
pub trait Active {
    #[zbus(property)]
    fn state(&self) -> zbus::Result<u32>;
    #[zbus(property)]
    fn uuid(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn devices(&self) -> zbus::Result<Vec<OwnedObjectPath>>;

    /// `StateChanged(state, reason)`. Named apart from the `State`
    /// property, whose change stream would otherwise take the same name.
    #[zbus(signal, name = "StateChanged")]
    fn activation(&self, state: u32, reason: u32) -> zbus::Result<()>;
}

/// `NMActiveConnectionStateReason`, in words.
pub fn reason(code: u32) -> String {
    match code {
        2 => "disconnected by request".to_string(),
        3 => "the device disconnected".to_string(),
        5 => "no usable IP configuration (no DHCP answer?)".to_string(),
        6 => "timed out".to_string(),
        9 => "no secrets (wrong password?)".to_string(),
        10 => "login failed (wrong password?)".to_string(),
        11 => "the profile was removed".to_string(),
        12 => "a connection it depends on failed".to_string(),
        14 => "the device went away".to_string(),
        other => format!("NetworkManager reason {other}"),
    }
}
