//! What the device's settings turn into on disk.
//!
//! These files, each written only when its content actually changes - an
//! unchanged render must never restart anything, because a restart is a
//! blank screen in a public place:
//!
//! * `/run/tessaro-kiosk/generated.env`: the settings as `KIOSK_*=value`
//!   lines, for `tessaro-kiosk.service` (`EnvironmentFile=`, after the image
//!   defaults) and for `tessaro-weston-config`. Only the keys that were set:
//!   everything else already comes from the `/usr/lib` defaults.
//! * `/etc/chromium/policies/managed/10-tessaro.json`: the image's policy with
//!   the device-API grants rewritten for the kiosk origin *as set*, not as
//!   built. Generated through serde, because Chromium drops the whole file
//!   on one syntax error with a single `SYSLOG(WARNING)`.
//! * `tessaro.txt` on a Raspberry Pi's boot partition: the settings the
//!   firmware reads at power-on (`device.gpu_mem`), pulled in by an
//!   `include` line at the end of `config.txt`. The image's `config.txt` has
//!   that line; one flashed before it gets it added here, once.
//!
//! Values need no quoting in the env file: the registry has already refused
//! every character systemd's parser would treat specially.

use std::collections::BTreeMap;
use std::net::SocketAddr;
use std::path::Path;

use serde_json::{Map, Value};

use crate::config::Env;
use crate::log::Log;
use crate::paths::Paths;
use crate::state;
use crate::store;

/// The grants that follow the kiosk origin: the device APIs and the
/// microphone, each without a prompt nobody is there to answer, and reaching
/// `http://127.0.0.1` (the file store) from an https site without a Local
/// Network Access prompt. Everything else in the policy is the image's.
const ORIGIN_POLICIES: &[&str] = &[
    "SerialAllowAllPortsForUrls",
    "WebHidAllowAllDevicesForUrls",
    "AudioCaptureAllowedUrls",
    "LocalNetworkAccessAllowedForUrls",
];

pub fn env_file(
    settings: &BTreeMap<String, String>,
    defaults: &dyn Env,
    live: &state::Live,
    log: &Log,
) -> String {
    let mut out = String::from(
        "# Generated by tessaro-agent from /data/tessaro/state.json. Do not edit:\n\
         # change a setting with `tessaro-ctl config set KEY=VALUE`, see `tessaro-ctl config keys`.\n",
    );
    let overrides = state::overrides(settings, log);
    for key in protocol::keys::KEYS {
        if key.env == "KIOSK_URL" {
            continue; // below, expanded
        }
        if key.env == "KIOSK_MAINTENANCE_URL" {
            continue; // a template; in maintenance mode it *is* KIOSK_URL below
        }
        if key.kind == protocol::keys::Kind::Template {
            // The debug template's `\n` is the one backslash a value may hold,
            // and systemd would eat it unquoted. Only the agent reads it, and
            // it reads state.json.
            continue;
        }
        if key.consumers == [protocol::keys::Consumer::Network] {
            // The network keys become NetworkManager keyfiles, never env:
            // no unit reads them, and an SSID has no business in an env file.
            continue;
        }
        if key.consumers == [protocol::keys::Consumer::Firmware] {
            // tessaro.txt, for the Pi firmware; no unit reads them.
            continue;
        }
        if key.consumers == [protocol::keys::Consumer::Audio] {
            // Applied to PipeWire by the agent, which reads state.json. No
            // unit reads them, and a change must not look like one to the
            // browser's env.
            continue;
        }
        if key.consumers == [protocol::keys::Consumer::Time] {
            // Applied through timedated and timesyncd by the agent, the same
            // way. The browser follows /etc/localtime, not TZ.
            continue;
        }
        if key.consumers.contains(&protocol::keys::Consumer::Proxy) {
            // The local proxy's config, root only; network.proxy.url carries
            // a password, which has no business in an env file the browser
            // unit reads.
            continue;
        }
        if let Some((env, value)) = overrides.iter().find(|(env, _)| *env == key.env) {
            out.push_str(&format!("{env}={value}\n"));
        }
    }

    // The kiosk URL goes out expanded, never as a template: the browser unit
    // opens ${KIOSK_URL} as it stands. Written whenever it differs from the
    // image default - set here, a default whose placeholders were filled, or
    // the maintenance page, so a reboot in maintenance never shows the site.
    let effective = state::Effective::new(defaults, settings, log).with_live(live.clone());
    if let Some(url) = effective.get("KIOSK_URL") {
        if defaults.get("KIOSK_URL").as_deref() != Some(url.as_str()) {
            out.push_str(&format!("KIOSK_URL={url}\n"));
        }
    }

    // Switches a flag turns into. systemd cannot make a flag conditional, so
    // the unit passes `$KIOSK_FPS_ARGS` (unbraced: empty means no argument
    // at all) and this is the one place that decides what it holds.
    if let Some((_, value)) = overrides
        .iter()
        .find(|(env, _)| *env == "KIOSK_FPS_COUNTER")
    {
        let args = if value == "1" {
            "--show-fps-counter"
        } else {
            ""
        };
        out.push_str(&format!("KIOSK_FPS_ARGS={args}\n"));
    }
    out
}

/// The device-API origins: the kiosk's, the self-test page's, and any extra
/// ones set, deduplicated and in that order. The kiosk's is browser.url's even
/// in maintenance mode, so toggling it never changes the policy.
pub fn device_origins(effective: &state::Effective, selftest_origin: &str) -> Vec<String> {
    let mut origins: Vec<String> = Vec::new();
    let kiosk_url = effective.kiosk_url().unwrap_or_default();
    let mut add = |origin: &str| {
        if !origin.is_empty() && !origins.iter().any(|known| known == origin) {
            origins.push(origin.to_string());
        }
    };

    if let Some(origin) = protocol::keys::origin_of(&kiosk_url) {
        add(origin);
    }
    add(selftest_origin);
    for origin in effective
        .get("KIOSK_DEVICE_ORIGINS")
        .unwrap_or_default()
        .split_whitespace()
    {
        add(origin);
    }
    origins
}

/// The policy entries that point Chromium at the local proxy. Present only
/// while network.proxy.url is set; the address never changes, so only
/// switching the proxy on or off changes the policy (and restarts the
/// browser). Loopback is bypassed by Chromium on its own.
const PROXY_POLICIES: &[&str] = &["ProxyMode", "ProxyServer", "ProxyBypassList"];

pub fn policy(base: &str, origins: &[String], proxy: Option<SocketAddr>) -> Result<String, String> {
    let mut document: Map<String, Value> = serde_json::from_str(&strict_json(base))
        .map_err(|err| format!("the base policy: {err}"))?;

    for name in ORIGIN_POLICIES {
        document.insert(
            name.to_string(),
            Value::Array(origins.iter().cloned().map(Value::String).collect()),
        );
    }
    for name in PROXY_POLICIES {
        document.remove(*name);
    }
    if let Some(proxy) = proxy {
        document.insert("ProxyMode".to_string(), Value::from("fixed_servers"));
        document.insert(
            "ProxyServer".to_string(),
            Value::from(format!("http://{proxy}")),
        );
        document.insert("ProxyBypassList".to_string(), Value::from("<-loopback>"));
    }

    let body = serde_json::to_string_pretty(&document).map_err(|err| err.to_string())?;
    Ok(format!(
        "// Generated by tessaro-agent from /usr/lib/tessaro-kiosk/policy.json,\n\
         // which carries the documentation for every entry. Do not edit: the\n\
         // device-API origins follow browser.url and browser.device_origins, set\n\
         // with tessaro-ctl. Check the result on chrome://policy.\n\
         {body}\n"
    ))
}

/// Chromium's policy loader accepts `//` and `/* */` comments and trailing
/// commas (`JSON_PARSE_CHROMIUM_EXTENSIONS`), and the shipped file uses all
/// of them to document itself. serde_json accepts none of them.
pub fn strict_json(text: &str) -> String {
    let chars: Vec<char> = text.chars().collect();
    let mut out = String::with_capacity(text.len());
    let mut at = 0;
    let mut in_string = false;

    while at < chars.len() {
        let ch = chars[at];
        if in_string {
            out.push(ch);
            if ch == '\\' && at + 1 < chars.len() {
                out.push(chars[at + 1]);
                at += 1;
            } else if ch == '"' {
                in_string = false;
            }
            at += 1;
            continue;
        }

        match (ch, chars.get(at + 1)) {
            ('"', _) => {
                in_string = true;
                out.push(ch);
                at += 1;
            }
            ('/', Some('/')) => {
                while at < chars.len() && chars[at] != '\n' {
                    at += 1;
                }
            }
            ('/', Some('*')) => {
                at += 2;
                while at < chars.len() && !(chars[at] == '*' && chars.get(at + 1) == Some(&'/')) {
                    at += 1;
                }
                at += 2;
            }
            (',', _) => {
                let next = chars[at + 1..]
                    .iter()
                    .enumerate()
                    .find(|(_, ch)| !ch.is_whitespace());
                // A comma followed, past whitespace and comments, by a closer.
                let trailing = match next {
                    Some((_, '}')) | Some((_, ']')) => true,
                    Some((offset, '/')) => {
                        let rest: String = chars[at + 1 + offset..].iter().collect();
                        strict_json(&rest).trim_start().starts_with(['}', ']'])
                    }
                    _ => false,
                };
                if !trailing {
                    out.push(',');
                }
                at += 1;
            }
            _ => {
                out.push(ch);
                at += 1;
            }
        }
    }
    out
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct Rendered {
    pub env_changed: bool,
    pub policy_changed: bool,
    /// What the Pi firmware reads at power-on changed: a reboot applies it.
    pub firmware_changed: bool,
    /// The local proxy's config was written, changed or removed.
    pub proxy_changed: bool,
}

/// Render every file from `settings` over the image `defaults`.
pub fn all(
    paths: &Paths,
    defaults: &dyn Env,
    settings: &BTreeMap<String, String>,
    log: &Log,
) -> Result<Rendered, String> {
    // What the device reports now: {device.name} when none is set, {device.id},
    // {network.ip} and the other read-only keys.
    let live = live(paths);

    let env_changed = store::replace_if_changed(
        &paths.generated_env(),
        env_file(settings, defaults, &live, log).as_bytes(),
        0o644,
    )
    .map_err(|err| format!("{}: {err}", paths.generated_env().display()))?;

    let effective = state::Effective::new(defaults, settings, log).with_live(live);
    let policy_changed = render_policy(paths, &effective)?;
    let firmware_changed = match &paths.boot_config_dir {
        Some(dir) => render_firmware(dir, &effective, log)?,
        None => false,
    };
    let proxy_changed = render_proxy(paths, &effective, log)?;

    Ok(Rendered {
        env_changed,
        policy_changed,
        firmware_changed,
        proxy_changed,
    })
}

/// The local proxy's config, or none: its absence keeps
/// `tessaro-proxy.service` from starting (`ConditionPathExists=`). 0600, as
/// it holds the upstream's credentials; tinyproxy reads it as root before
/// it drops to its own user.
fn render_proxy(paths: &Paths, effective: &state::Effective, log: &Log) -> Result<bool, String> {
    let url = effective.get("KIOSK_PROXY_URL").unwrap_or_default();
    let bypass = effective.get("KIOSK_PROXY_BYPASS").unwrap_or_default();
    let body = match proxy_config(&url, &bypass, paths.proxy_listen) {
        Ok(body) => body,
        // Validated at `config set`; a state.json from elsewhere that does
        // not parse means no proxy, never a broken config.
        Err(err) => {
            log.info(format!("network.proxy.url is not used: {err}"));
            None
        }
    };
    let path = &paths.proxy_config;
    match body {
        Some(body) => store::replace_if_changed(path, body.as_bytes(), 0o600)
            .map_err(|err| format!("{}: {err}", path.display())),
        None => match std::fs::remove_file(path) {
            Ok(()) => Ok(true),
            Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(false),
            Err(err) => Err(format!("{}: {err}", path.display())),
        },
    }
}

/// tinyproxy's config for network.proxy.url and .bypass, or `None` without
/// a proxy. The directives are tinyproxy 1.11's (`conf.c`): every
/// connection to the one upstream, with its credentials, except loopback
/// and the bypass entries (`Upstream none`), which go direct. No
/// `ConnectPort`, so a tunnel may go to any port; no `LogFile`, so it logs
/// to stdout, into the journal.
pub fn proxy_config(url: &str, bypass: &str, listen: SocketAddr) -> Result<Option<String>, String> {
    if url.trim().is_empty() {
        return Ok(None);
    }
    let proxy = protocol::keys::parse_proxy(url)?;
    let mut out = format!(
        "# Generated by tessaro-agent from network.proxy.url and network.proxy.bypass.\n\
         # Do not edit: `tessaro-ctl network proxy set`. Holds the upstream's credentials.\n\
         User tinyproxy\n\
         Group nogroup\n\
         Listen {}\n\
         Port {}\n\
         Allow 127.0.0.1\n\
         Timeout 600\n\
         MaxClients 100\n\
         DisableViaHeader Yes\n\
         XTinyproxy No\n\
         LogLevel Notice\n\
         Upstream none \"localhost\"\n\
         Upstream none \"127.0.0.0/8\"\n",
        listen.ip(),
        listen.port()
    );
    for entry in protocol::keys::parse_bypass(bypass)? {
        out.push_str(&format!("Upstream none \"{entry}\"\n"));
    }
    out.push_str(&format!("Upstream {}\n", proxy.upstream()));
    Ok(Some(out))
}

/// The file `config.txt` includes, beside it on the boot partition.
const FIRMWARE_FILE: &str = "tessaro.txt";
/// What `config.txt` has to end with. `[all]` first, because an include
/// inside a conditional section (`[pi4]`) would apply to that board only.
const FIRMWARE_INCLUDE: &str = "[all]\ninclude tessaro.txt\n";

/// `tessaro.txt` from the settings, and the `include` for it in
/// `config.txt` if that lacks one. Whether either changed.
fn render_firmware(dir: &Path, effective: &state::Effective, log: &Log) -> Result<bool, String> {
    let file = dir.join(FIRMWARE_FILE);
    let body = firmware_file(effective);
    let written = store::replace_if_changed_on_vfat(&file, body.as_bytes())
        .map_err(|err| format!("{}: {err}", file.display()))?;

    let config = dir.join("config.txt");
    let included = match std::fs::read_to_string(&config) {
        Ok(text) => match with_include(&text) {
            Some(text) => {
                store::replace_if_changed_on_vfat(&config, text.as_bytes())
                    .map_err(|err| format!("{}: {err}", config.display()))?;
                log.info(format!(
                    "added `include {FIRMWARE_FILE}` to {}",
                    config.display()
                ));
                true
            }
            None => false,
        },
        // No config.txt means no firmware reading it: nothing to wire up.
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => false,
        Err(err) => return Err(format!("{}: {err}", config.display())),
    };
    Ok(written || included)
}

/// The settings the firmware reads, one `config.txt` line each. Depends on
/// the settings only, so an unchanged render writes nothing.
fn firmware_file(effective: &state::Effective) -> String {
    let mut out = String::from(
        "# Written by tessaro-agent from the device's settings and read by the\n\
         # firmware at power-on, through the include at the end of config.txt.\n\
         # Change it with `tessaro-ctl config set`; edits here are overwritten.\n",
    );
    let gpu_mem = crate::config::Env::get(effective, "KIOSK_GPU_MEM").unwrap_or_default();
    if !gpu_mem.is_empty() {
        out.push_str(&format!("gpu_mem={gpu_mem}\n"));
    }
    out
}

/// `config.txt` with the include appended, or `None` if it has one. The
/// firmware applies lines in order and a later one wins, so it goes last.
/// Nothing else in the file is touched.
fn with_include(config: &str) -> Option<String> {
    let include = format!("include {FIRMWARE_FILE}");
    if config.lines().any(|line| line.trim() == include) {
        return None;
    }
    let mut out = config.to_string();
    if !out.is_empty() && !out.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(FIRMWARE_INCLUDE);
    Some(out)
}

/// The name derived from the node id, or `None` without a machine id (a
/// development host pointed at a sandbox).
pub fn derived_name(paths: &Paths) -> Option<String> {
    crate::identity::read_node_id(&paths.machine_id)
        .ok()
        .map(|id| crate::identity::friendly_name(&id))
}

/// Everything the device reports rather than stores, as the read-only keys
/// see it right now. Blocking: sysfs, /proc and one getifaddrs.
pub fn live(paths: &Paths) -> state::Live {
    let mut values = crate::net::values(&crate::net::snapshot(paths));
    if let Ok(storage) = crate::storage::snapshot(paths) {
        values.extend(crate::storage::values(&storage));
    }
    if let Ok(id) = crate::identity::read_node_id(&paths.machine_id) {
        values.insert("device.id".to_string(), id);
    }
    state::Live {
        derived_name: derived_name(paths),
        values,
    }
}

fn render_policy(paths: &Paths, effective: &state::Effective) -> Result<bool, String> {
    let base = match std::fs::read_to_string(&paths.policy_base) {
        Ok(base) => base,
        // No base (a development host): leave the policy alone rather than
        // write one that carries nothing but the grants.
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(false),
        Err(err) => return Err(format!("{}: {err}", paths.policy_base.display())),
    };

    let origins = device_origins(effective, &paths.selftest_origin);
    let proxy = effective
        .get("KIOSK_PROXY_URL")
        .filter(|url| protocol::keys::parse_proxy(url).is_ok())
        .map(|_| paths.proxy_listen);
    let body = policy(&base, &origins, proxy)?;
    write(&paths.policy, &body)
}

fn write(path: &Path, body: &str) -> Result<bool, String> {
    store::replace_if_changed(path, body.as_bytes(), 0o644)
        .map_err(|err| format!("{}: {err}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    fn settings(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect()
    }

    fn factory() -> HashMap<String, String> {
        [("KIOSK_URL".to_string(), "http://127.0.0.1/".to_string())].into()
    }

    #[test]
    fn the_env_file_holds_only_what_was_set_in_registry_order() {
        let log = Log::buffered(true);
        let text = env_file(
            &settings(&[("screen.osk", "never"), ("browser.url", "https://a.test/")]),
            &factory(),
            &state::Live::default(),
            &log,
        );

        let lines: Vec<&str> = text.lines().filter(|line| !line.starts_with('#')).collect();
        assert_eq!(lines, ["KIOSK_OSK=never", "KIOSK_URL=https://a.test/"]);

        let untouched = env_file(&BTreeMap::new(), &factory(), &state::Live::default(), &log);
        assert!(
            untouched.lines().all(|line| line.starts_with('#')),
            "{untouched}"
        );
    }

    #[test]
    fn the_env_file_carries_the_url_expanded_never_the_template() {
        let log = Log::buffered(true);
        let text = env_file(
            &settings(&[
                ("browser.url", "https://{data.shop}.test/?t={data.table}"),
                ("data.shop", "north"),
                ("data.table", "7 a"),
            ]),
            &factory(),
            &state::Live::default(),
            &log,
        );

        assert!(
            text.contains("KIOSK_URL=https://north.test/?t=7%20a\n"),
            "{text}"
        );
        assert!(!text.contains('{'), "{text}");
    }

    #[test]
    fn the_debug_template_never_reaches_the_env_file() {
        let log = Log::buffered(true);
        let text = env_file(
            &settings(&[
                ("browser.debug.enable", "1"),
                (
                    "browser.debug.template",
                    "IP {network.ip}\\nGW {network.gateway}",
                ),
            ]),
            &factory(),
            &state::Live::default(),
            &log,
        );

        let lines: Vec<&str> = text.lines().filter(|line| !line.starts_with('#')).collect();
        assert_eq!(lines, ["KIOSK_DEBUG_SCREEN=1"]);
    }

    #[test]
    fn audio_settings_never_reach_the_env_file() {
        let log = Log::buffered(true);
        let text = env_file(
            &settings(&[
                ("audio.output", "hdmi"),
                ("audio.volume", "40"),
                ("screen.osk", "never"),
            ]),
            &factory(),
            &state::Live::default(),
            &log,
        );

        let lines: Vec<&str> = text.lines().filter(|line| !line.starts_with('#')).collect();
        assert_eq!(lines, ["KIOSK_OSK=never"]);
    }

    #[test]
    fn a_placeholder_in_the_host_moves_the_device_grants() {
        let log = Log::buffered(true);
        let set = settings(&[
            ("browser.url", "https://{data.shop}.test/"),
            ("data.shop", "north"),
        ]);
        let defaults = factory();
        let effective = state::Effective::new(&defaults, &set, &log);

        assert_eq!(
            device_origins(&effective, "http://127.0.0.1"),
            ["https://north.test", "http://127.0.0.1"]
        );
    }

    #[test]
    fn origins_follow_the_kiosk_url_as_set() {
        let defaults: HashMap<String, String> =
            [("KIOSK_URL".to_string(), "http://127.0.0.1/".to_string())].into();
        let log = Log::buffered(true);

        let factory = state::Effective::new(&defaults, &BTreeMap::new(), &log);
        assert_eq!(
            device_origins(&factory, "http://127.0.0.1"),
            ["http://127.0.0.1"]
        );

        let deployed = settings(&[
            ("browser.url", "https://shop.test/welcome?x=1"),
            (
                "browser.device_origins",
                "https://tools.test http://127.0.0.1",
            ),
        ]);
        let deployed = state::Effective::new(&defaults, &deployed, &log);
        assert_eq!(
            device_origins(&deployed, "http://127.0.0.1"),
            [
                "https://shop.test",
                "http://127.0.0.1",
                "https://tools.test"
            ]
        );
    }

    #[test]
    fn the_shipped_policy_template_parses_and_is_rewritten() {
        let template = include_str!(
            "../../../meta-tessaro-distro/recipes-browser/tessaro-kiosk/files/tessaro-kiosk-policy.json.in"
        );
        // What do_install substitutes into it.
        let base = template
            .replace("@kiosk-origin@", "http://127.0.0.1")
            .replace("@device-origins@", "\"http://127.0.0.1\"");

        let body = policy(
            &base,
            &["https://a.test".to_string(), "http://127.0.0.1".to_string()],
            None,
        )
        .unwrap();
        let parsed: Value = serde_json::from_str(&strict_json(&body)).unwrap();

        assert_eq!(
            parsed["SerialAllowAllPortsForUrls"],
            serde_json::json!(["https://a.test", "http://127.0.0.1"])
        );
        assert_eq!(
            parsed["WebHidAllowAllDevicesForUrls"],
            parsed["SerialAllowAllPortsForUrls"]
        );
        assert_eq!(
            parsed["LocalNetworkAccessAllowedForUrls"],
            parsed["SerialAllowAllPortsForUrls"]
        );
        assert_eq!(
            parsed["AudioCaptureAllowedUrls"],
            parsed["SerialAllowAllPortsForUrls"]
        );
        assert_eq!(parsed["TranslateEnabled"], Value::Bool(false));
        assert!(body.starts_with("// Generated by tessaro-agent"));
        assert!(parsed.get("ProxyMode").is_none());
    }

    #[test]
    fn a_proxy_points_chromium_at_the_local_one_and_off_takes_it_out() {
        let listen: SocketAddr = "127.0.0.1:3128".parse().unwrap();
        let on = policy("{}", &[], Some(listen)).unwrap();
        let parsed: Value = serde_json::from_str(&strict_json(&on)).unwrap();
        assert_eq!(parsed["ProxyMode"], "fixed_servers");
        assert_eq!(parsed["ProxyServer"], "http://127.0.0.1:3128");
        assert_eq!(parsed["ProxyBypassList"], "<-loopback>");

        let off = policy(&strict_json(&on), &[], None).unwrap();
        let parsed: Value = serde_json::from_str(&strict_json(&off)).unwrap();
        assert!(parsed.get("ProxyMode").is_none());
        assert!(parsed.get("ProxyServer").is_none());
    }

    #[test]
    fn the_local_proxy_carries_the_upstream_its_credentials_and_the_bypass() {
        let listen: SocketAddr = "127.0.0.1:3128".parse().unwrap();
        assert_eq!(proxy_config("", "a.test", listen).unwrap(), None);

        let body = proxy_config(
            "http://jan:pa%24s@proxy.corp.test:8080",
            ".corp.test,10.0.0.0/8",
            listen,
        )
        .unwrap()
        .unwrap();
        assert!(body.contains("\nListen 127.0.0.1\nPort 3128\n"), "{body}");
        assert!(
            body.contains("\nUpstream http jan:pa$s@proxy.corp.test:8080\n"),
            "{body}"
        );
        assert!(body.contains("\nUpstream none \"127.0.0.0/8\"\n"), "{body}");
        assert!(body.contains("\nUpstream none \".corp.test\"\n"), "{body}");
        assert!(body.contains("\nUpstream none \"10.0.0.0/8\"\n"), "{body}");
        assert!(!body.contains("ConnectPort"), "{body}");

        let socks = proxy_config("socks5://10.0.0.9:1080", "", listen)
            .unwrap()
            .unwrap();
        assert!(
            socks.ends_with("Upstream socks5 10.0.0.9:1080\n"),
            "{socks}"
        );
    }

    #[test]
    fn the_proxy_config_is_root_only_and_goes_away_with_the_proxy() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let log = Log::buffered(true);
        let config = dir.path().join("proxy/tinyproxy.conf");
        let env: HashMap<String, String> = [
            ("KIOSK_RUN_DIR", dir.path().join("run")),
            ("KIOSK_POLICY", dir.path().join("policy.json")),
            ("KIOSK_POLICY_BASE", dir.path().join("missing-base.json")),
            ("KIOSK_PROXY_CONFIG", config.clone()),
        ]
        .into_iter()
        .map(|(name, path)| (name.to_string(), path.display().to_string()))
        .collect();
        let paths = Paths::load(&env);
        let mut settings = BTreeMap::new();
        settings.insert(
            "network.proxy.url".to_string(),
            "http://u:p@h.test:1".to_string(),
        );

        assert!(all(&paths, &env, &settings, &log).unwrap().proxy_changed);
        assert_eq!(
            std::fs::metadata(&config).unwrap().permissions().mode() & 0o777,
            0o600
        );
        assert!(!all(&paths, &env, &settings, &log).unwrap().proxy_changed);
        let env_file = std::fs::read_to_string(paths.generated_env()).unwrap();
        assert!(!env_file.contains("PROXY"), "{env_file}");

        settings.clear();
        assert!(all(&paths, &env, &settings, &log).unwrap().proxy_changed);
        assert!(!config.exists());
    }

    #[test]
    fn strict_json_keeps_strings_intact() {
        let text = r#"{
  // a comment
  "a": "http://x/y", /* block */
  "b": ["//not a comment", "a,]"],
  "c": 1, // trailing comma follows
}"#;
        let value: Value = serde_json::from_str(&strict_json(text)).unwrap();
        assert_eq!(value["a"], "http://x/y");
        assert_eq!(value["b"][0], "//not a comment");
        assert_eq!(value["b"][1], "a,]");
        assert_eq!(value["c"], 1);
    }

    #[test]
    fn a_trailing_comma_before_a_comment_and_a_closer_is_dropped() {
        let value: Value = serde_json::from_str(&strict_json("[1, 2, // x\n]")).unwrap();
        assert_eq!(value, serde_json::json!([1, 2]));
    }

    #[test]
    fn rendering_twice_changes_nothing_the_second_time() {
        let dir = tempfile::tempdir().unwrap();
        let log = Log::buffered(true);
        let env: HashMap<String, String> = [
            (
                "KIOSK_RUN_DIR".to_string(),
                dir.path().join("run").display().to_string(),
            ),
            (
                "KIOSK_POLICY".to_string(),
                dir.path().join("policy.json").display().to_string(),
            ),
            (
                "KIOSK_POLICY_BASE".to_string(),
                dir.path().join("base.json").display().to_string(),
            ),
            (
                "KIOSK_PROXY_CONFIG".to_string(),
                dir.path().join("tinyproxy.conf").display().to_string(),
            ),
        ]
        .into();
        let paths = Paths::load(&env);
        std::fs::write(&paths.policy_base, "{\"TranslateEnabled\": false,}").unwrap();
        let defaults: HashMap<String, String> =
            [("KIOSK_URL".to_string(), "http://127.0.0.1/".to_string())].into();
        let set = settings(&[("browser.url", "https://a.test/")]);

        assert_eq!(
            all(&paths, &defaults, &set, &log).unwrap(),
            Rendered {
                env_changed: true,
                policy_changed: true,
                firmware_changed: false,
                proxy_changed: false
            }
        );
        assert_eq!(
            all(&paths, &defaults, &set, &log).unwrap(),
            Rendered::default()
        );

        let same_origin = settings(&[("browser.url", "https://a.test/other")]);
        assert_eq!(
            all(&paths, &defaults, &same_origin, &log).unwrap(),
            Rendered {
                env_changed: true,
                policy_changed: false,
                firmware_changed: false,
                proxy_changed: false
            }
        );

        // Maintenance mode moves what the browser opens, never the grants:
        // a policy change would restart the browser on a public screen.
        let mut maintenance = same_origin.clone();
        maintenance.insert("browser.maintenance.enable".into(), "1".into());
        maintenance.insert(
            "browser.maintenance.url".into(),
            "http://127.0.0.1/maintenance.html".into(),
        );
        assert_eq!(
            all(&paths, &defaults, &maintenance, &log).unwrap(),
            Rendered {
                env_changed: true,
                policy_changed: false,
                firmware_changed: false,
                proxy_changed: false
            }
        );
        let env = std::fs::read_to_string(paths.generated_env()).unwrap();
        assert!(
            env.contains("KIOSK_URL=http://127.0.0.1/maintenance.html\n"),
            "{env}"
        );
    }

    /// Paths with a Pi boot partition in `dir`, holding `config`.
    fn pi(dir: &Path, config: &str) -> Paths {
        let boot = dir.join("boot");
        std::fs::create_dir_all(&boot).unwrap();
        std::fs::write(boot.join("config.txt"), config).unwrap();
        let env: HashMap<String, String> = [
            ("KIOSK_RUN_DIR", dir.join("run")),
            ("KIOSK_POLICY", dir.join("policy.json")),
            ("KIOSK_POLICY_BASE", dir.join("missing-base.json")),
            ("KIOSK_PROXY_CONFIG", dir.join("tinyproxy.conf")),
            ("KIOSK_BOOT_CONFIG_DIR", boot),
        ]
        .into_iter()
        .map(|(name, path)| (name.to_string(), path.display().to_string()))
        .collect();
        Paths::load(&env)
    }

    #[test]
    fn gpu_mem_is_written_for_the_firmware_and_only_when_it_changes() {
        let dir = tempfile::tempdir().unwrap();
        let log = Log::buffered(true);
        let paths = pi(dir.path(), "enable_uart=1\ndtoverlay=vc4-kms-v3d\n");
        let boot = paths.boot_config_dir.clone().unwrap();
        let defaults: HashMap<String, String> = HashMap::new();
        let set = settings(&[("device.gpu_mem", "128")]);

        assert!(all(&paths, &defaults, &set, &log).unwrap().firmware_changed);
        let file = std::fs::read_to_string(boot.join("tessaro.txt")).unwrap();
        assert!(file.ends_with("\ngpu_mem=128\n"), "{file}");
        assert!(!file.contains("KIOSK_"), "{file}");
        let env = std::fs::read_to_string(paths.generated_env()).unwrap();
        assert!(!env.contains("GPU_MEM"), "{env}");

        assert!(!all(&paths, &defaults, &set, &log).unwrap().firmware_changed);

        // Unset: the firmware's own default, so no line at all.
        assert!(
            all(&paths, &defaults, &BTreeMap::new(), &log)
                .unwrap()
                .firmware_changed
        );
        let file = std::fs::read_to_string(boot.join("tessaro.txt")).unwrap();
        assert!(!file.contains("gpu_mem"), "{file}");
    }

    #[test]
    fn config_txt_gets_the_include_once_and_nothing_else() {
        let dir = tempfile::tempdir().unwrap();
        let log = Log::buffered(true);
        let paths = pi(dir.path(), "enable_uart=1\n[pi4]\narm_boost=1");
        let config = paths.boot_config_dir.clone().unwrap().join("config.txt");
        let defaults: HashMap<String, String> = HashMap::new();

        all(&paths, &defaults, &BTreeMap::new(), &log).unwrap();
        let text = std::fs::read_to_string(&config).unwrap();
        assert_eq!(
            text,
            "enable_uart=1\n[pi4]\narm_boost=1\n[all]\ninclude tessaro.txt\n"
        );

        all(&paths, &defaults, &BTreeMap::new(), &log).unwrap();
        assert_eq!(std::fs::read_to_string(&config).unwrap(), text);
    }

    #[test]
    fn a_config_txt_from_the_image_is_left_alone() {
        assert_eq!(with_include("a=1\n[all]\ninclude tessaro.txt\n"), None);
        assert_eq!(with_include("a=1\n  include tessaro.txt  \n"), None);
    }

    #[test]
    fn without_pi_firmware_nothing_is_written_to_a_boot_partition() {
        let dir = tempfile::tempdir().unwrap();
        let log = Log::buffered(true);
        let mut paths = pi(dir.path(), "enable_uart=1\n");
        let boot = paths.boot_config_dir.take().unwrap();
        let set = settings(&[("device.gpu_mem", "128")]);

        let rendered = all(&paths, &HashMap::<String, String>::new(), &set, &log).unwrap();
        assert!(!rendered.firmware_changed);
        assert!(!boot.join("tessaro.txt").exists());
        assert_eq!(
            std::fs::read_to_string(boot.join("config.txt")).unwrap(),
            "enable_uart=1\n"
        );
    }
}
