# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-tessaro-distro"
BBFILE_PATTERN_meta-tessaro-distro = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-tessaro-distro = "20"

LAYERDEPENDS_meta-tessaro-distro = " \
    core \
    meta-moonforge-distro \
"
LAYERSERIES_COMPAT_meta-tessaro-distro = "scarthgap"
