require conf/distro/moonforge.conf

DISTRO = "tessaro"
DISTRO_NAME = "Tessaro OS"
DISTRO_VERSION = "0.1"

MAINTAINER = "Ahmed Al Hafoudh <alhafoudh@freevision.sk>"

# Default hostname; base-files would otherwise use ${MACHINE}.
hostname:pn-base-files = "tessaro"
